name: Backup and Test MongoDB Atlas

on:
  schedule:
    - cron: '0 4 * * *' # Everyday at 4 am
  workflow_dispatch: # Possibility to launch manualy

jobs:
  backup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.0.0_amd64.deb -O mongodb-mongosh.deb
          sudo dpkg -i mongodb-mongosh.deb || sudo apt install -f -y openssl

      - name: Create MongoDB Dump
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          today=$(date +"%Y-%m-%d")
          echo "------------LOG------------ TODAY IS $today ------------LOG------------"
          mongodump --uri="$MONGODB_URL" -d db-production --out=backup-db-production-$today

      - name: Restore Dump to MongoDB Atlas Test Cluster
        env:
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
        run: |
          today=$(date +"%Y-%m-%d")
          echo "------------LOG------------ TODAY IS $today ------------LOG------------"
          mongorestore --uri="$TEST_MONGODB_URL" backup-db-production-$today --nsFrom="db-production.*" --nsTo="db-test.*" --drop 
