name: Backup and Test MongoDB Atlas

on:
  schedule:
    - cron: '0 4 * * *' # Everyday at 4 am
  workflow_dispatch: # Possibility to launch manualy

jobs:
  backup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update         
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb -O mongodb-mongotools.deb
          sudo dpkg -i mongodb-mongotools.deb || sudo apt install -f -y openssl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Create MongoDB Dump
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          today=$(date +"%Y-%m-%d")
          mongodump --uri="$MONGODB_URL" -d db-production --out=backup-db-production-$today

      - name: Restore Dump to MongoDB Atlas Test Cluster
        env:
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
        run: |
          today=$(date +"%Y-%m-%d")
          mongorestore --uri="$TEST_MONGODB_URL" backup-db-production-$today --nsFrom="db-production.*" --nsTo="db-test.*" --drop

      - name: Encrypt Dump
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          today=$(date +"%Y-%m-%d")
          tar -czf backup-db-production-$today.tar.gz backup-db-production-$today
          openssl enc -aes-256-cbc -salt -in backup-db-production-$today.tar.gz -out backup-db-production-$today.tar.gz.enc -k "$ENCRYPTION_KEY"
          rm -rf backup-db-production-$today backup-db-production-$today.tar.gz
          
      - name: Upload Dump to Azure Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          today=$(date +"%Y-%m-%d")
          az storage blob upload \
            --container-name backup-container \
            --file backup-db-production-$today.tar.gz.enc \
            --name backup-db-production-$today.tar.gz.enc \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
